---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo1
  name: demo1
spec:
  containers:
    - image: k8s.gcr.io
      name: demo1
      ports:
        - containerPort: 8080
          protocol: TCP
