---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo1
  name: demo1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: demo1
  type: ClusterIP
